version: '2'
services:
  preferences-app:
    image: preferences
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://preferences-postgresql:5432/preferences
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://preferences-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://preferences-elasticsearch:9200
    ports:
      - 8080:8080
  preferences-postgresql:
    extends:
      file: postgresql.yml
      service: preferences-postgresql
  preferences-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: preferences-elasticsearch
